bob = User.create(name: "Bob")
steve = User.create(name: "Steve")
carl = User.create(name: "Carl")
marc = User.create(name: "Marc")
jane = User.create(name: "Jane")
sarah = User.create(name: "Sarah")
jenny = User.create(name: "Jenny")

forkeys = Publisher.create(name: "Forkeys, Inc")
calums = Publisher.create(name: "Calums, Inc")
taker = Publisher.create(name: "Taker, Inc")
footer = Publisher.create(name: "Footer, Inc")
carlisle = Publisher.create(name: "Carlisle, Inc")
southebys = Publisher.create(name: "Southebys, Inc")


bob.books.create(publisher_id: forkeys.id)
steve.books.create(publisher_id: calums.id)
carl.books.create(publisher_id: taker.id)
marc.books.create(publisher_id: footer.id)
jane.books.create(publisher_id: carlisle.id)
sarah.books.create(publisher_id: southebys.id)
